const express = require("express")
const multer = require("multer")
const upload = multer()
const uploadCloud = require("../../middlewares/admin/uploadCloud.middleware")
const router = express()
const controller = require("../../controllers/admin/account.controller")
router.get("/", controller.index)
router.get("/create", controller.create)
router.post("/create",upload.single('avatar'), uploadCloud.uploadSingle, controller.createPost)
router.patch("/change-status/:id/:status", controller.changeStatus)
router.get("/edit/:id", controller.edit)
router.patch("/edit/:id",upload.single("avatar"), uploadCloud.uploadSingle, controller.editPatch)
router.delete("/delete/:id", controller.delete)
router.get("/detail/:id", controller.detail)
module.exports = router