const express = require("express")
const controller = require("../../controllers/admin/product.controller")
const router = express()
const multer  = require('multer')
const upload = multer()
const uploadCloud = require("../../middlewares/admin/uploadCloud.middleware")
const validate = require("../../validates/admin/product.validate")
router.get("/", controller.index)
router.patch("/change-status/:status/:id", controller.changeStatus)
router.patch("/change-multi", controller.changeMultiPatch)                                                                                                                
router.delete("/delete/:id", controller.deleteItem)
router.get("/trash", controller.trash)
router.delete("/deleteVv/:id", controller.deleteItemVv)
router.patch("/:id", controller.restoreItemPatch)
router.get("/create", controller.createItem)
router.post("/create",upload.single("thumbnail"), uploadCloud.uploadSingle,validate.createPost, controller.createPost)
router.get("/edit/:id", controller.edit)
router.patch("/edit/:id",upload.single("thumbnail"),uploadCloud.uploadSingle,validate.createPost, controller.editPost)
router.get("/detail/:id", controller.detail)
module.exports = router