const express = require("express")
const controller = require("../../controllers/admin/product.controller")
const router = express()
const multer  = require('multer')
const storage =  require("../../helper/storageMulter.helper")
const upload = multer({storage : storage})
const validate = require("../../validates/admin/product.vallidate")
router.get("/", controller.index)
router.patch("/change-status/:status/:id", controller.changeStatus)
router.patch("/change-multi", controller.changeMultiPatch)                                                                                                                
router.delete("/delete/:id", controller.deleteItem)
router.get("/trash", controller.trash)
router.delete("/deleteVv/:id", controller.deleteItemVv)
router.patch("/:id", controller.restoreItemPatch)
router.get("/create", controller.createItem)
router.post("/create",upload.single("thumbnail"),validate.createPost, controller.createPost)
router.get("/edit/:id", controller.edit)
router.patch("/edit/:id",upload.single("thumbnail"),validate.createPost, controller.editPost)
module.exports = router