const homeRouter = require("./home.route")
const productRouter = require("./product.route")
const searchRouter = require("./search.route")
const cartRouter = require("./cart.route")
const checkOutRouter = require("./checkout.route")
const userRouter = require("./user.route")
const createTreeMiddleware = require("../../middlewares/client/category.middleware")
const cartMiddleware = require("../../middlewares/client/cart.middleware")
const userMiddleware = require("../../middlewares/client/user.middleware")
const generalSettingMiddleware = require('../../middlewares/admin/general-setting.middleware')
module.exports = (app) => {
    app.use(createTreeMiddleware.caterogy)
    app.use(cartMiddleware.cart)
    app.use(userMiddleware.user)
    app.use(generalSettingMiddleware.generalSettting)
    app.use("/", homeRouter)
    app.use("/products", productRouter)
    app.use("/search", searchRouter)
    app.use("/cart", cartRouter)
    app.use("/checkout", checkOutRouter)
    app.use("/user", userRouter)
}